baseURL: https://junnayanaiportfolio.netlify.app/ 
languageCode: en-us
title: Junna's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    #buttonText: My Linkedin
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Junna Yanai
  blog: {}
  contact:
    address:
      - city: LONDON, NW1 4SA
        country: UNITED KINGDOM
        street: REGENT'S PARK
        #title: 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jyanai.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7585-494103
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/junna.yanai.3/
      #- icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Jubba8713
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/junnayanai/
  image: 'https://media-exp1.licdn.com/dms/image/C5603AQEwrZvNBegIkA/profile-displayphoto-shrink_400_400/0/1626730549606?e=1635379200&v=beta&t=bIjjy5KX2zowqMNBRWk57hmtavIH0b-NpfxZkBrAzMU'
  name: Junna Yanai
  navigation:
    button1:
      - name: My Linkedin
        url: 'https://www.linkedin.com/in/junnayanai/'
    button2: 
      - name: My CV
        url: 'https://drive.google.com/file/d/1dQQGpguJLZPYK1KqeRte1GBR4VLqi9E2/view?usp=sharing'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/AboutMe
      - name: GGplot Project 1
        url: blogs/Project1
      - name: GGplot Project 2
        url: blogs/Project2
      - name: Past Research Paper
        url: blogs/ResearchPaper
      - name: Bloomberg Project
        url: blogs/Bloomberg
    menu: Menu
    subtitle: Portfolio Website
    title: Junna Yanai
  tiles:
    enable: yes
    showcase:
      - image: pic07.jpg
        subtitle: Masters in Analytics and Management Student at London Business School with international experience from the United States, France, and Japan, passionate about digitization and analytics. 
        title: About Me
        url: blogs/AboutMe
      - image: pic08.jpg
        subtitle: Please take a look at my CV.
        title: My CV
        url: 'https://drive.google.com/file/d/1dQQGpguJLZPYK1KqeRte1GBR4VLqi9E2/view?usp=sharing'
      - image: pic10.jpg
        subtitle: In this Project, my team and I visualized the trends from various datasets from alcohol consumption patterns around the world to financial stock return analysis.
        title: Ggplot Project 1
        url: blogs/Project1
      - image: pic09.jpg
        subtitle: In this project, my team and I utilized tidyverse and ggplot packages to visualize data on topics ranging from temperatures and climate change to social media usage via the GSS.
        title: Ggplot Project 2
        url: blogs/project2
      - image: picAbstract.jpg
        subtitle: During my undergraduate, I published a thesis on The Effect of CEO Profile and Company Statistics on Envrionmental and Social Disclosures in the Japanese Industrials Sector.
        title: Past Research Paper
        url: blogs/ResearchPaper
      - image: ARIMA.jpg
        subtitle: During my 3rd year in undergraduate studies, I participated in the Bloomberg ESG Investment Contest 2020.
        title: Bloomberg Project
        url: blogs/Bloomberg
  #two:
    #buttonText: My Linkedin
    #enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      #\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
     # condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      #pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: 
    #url: https://www.linkedin.com/in/junnayanai/
